---
- name: Only supports Centos 7 for the time being
  assert:
    that:
      - ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'
  tags: ['always']

- block:
  - name: Create a dedicated group to run Jupyter
    group:
      name: jupyter
      gid: 2841
      system: yes
      state: present

  - name: Create a dedicated user to run Jupyter
    user:
      name: jupyter
      groups: jupyter
      uid: 2841
      system: yes
      createhome: yes
      state: present

  - name: Setup Jupyter notebook directory
    file:
      path: /data
      state: directory
      owner: jupyter
      group: jupyter
      mode: 0777
  tags: ['always']

- import_tasks: format.yml
  tags: ['never']

- import_tasks: install.yml
  tags: ['install']

- import_tasks: config.yml
  tags: ['config']
